---
title: "summary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# loads in data
df <- read.csv("./data/ilodata.csv", stringsAsFactors = FALSE)

# creates dataframe of surveys to embed in table
surveys <- as.data.frame(unique(df$Survey_Label))
colnames(surveys) <- "ILO Unemployment Surveys"
```

# Summary
-----------

## About the Source

For this project we used data collected by the International Labor Organization, an organization with the mission of promoting social justice and internationally recognized human and labor rights.

The ILO was created as a result of the treaty of Versailles following the end of World War I. 187 countries are members of the ILO, meaning they partake in the International Labor Conference, are supervised by the ILO and collaborate with ILO's projects and research. To learn more about the ILO, check here (insert hyperlink).

## Urbanization and Unemployment

On a global, national, or regional scale, urbanization is an intensely complicated phenomena. Through modern history, societies around the world have undergone huge changes due to industrial shifts and the following formation of, and migration into cities. According to the World Health Organization, in 1960 34% of the worlds population resided in cities, by 2014 that number became 54%. WHO states: "The global urban population is expected to grow approximately 1.84% per year between 2015 and 2020, 1.63% per year between 2020 and 2025, and 1.44% per year between 2025 and 2030."

Although the world has steadily urbanized over the last 50+ years, the. Events like war, political revolution, industry collapse, technology shifts, poverty and more drive populations in both directions. For this project we examined a factor that is implicated in many of the prior phenomenas; unemployment.

## Methods

### Data

This data was collected by the ILO via several different large scale surveys and census collections. Survey data provides the mean unemployment percentage by country, age pools, gender, and rural/urban. Areas are considered urban or rural based on the population density defined by whether or not there are more than 400 people per square kilometer.

`r kable(surveys, format = 'markdown')`


The ILO states the following about their definition of unemployment:

### Unemployment Definition

The unemployed comprise all persons of working age who were: a) without work during the reference period, i.e. were not in paid employment or self-employment; b) currently available for work, i.e. were available for paid employment or self-employment during the reference period; and c) seeking work, i.e. had taken specific steps in a specified recent period to seek paid employment or self-employment. For purposes of international comparability, the period of job search is often defined as the preceding four weeks, but this varies from country to country. The specific steps taken to seek employment may include registration at a public or private employment exchange; application to employers; checking at worksites, farms, factory gates, market or other assembly places; placing or answering newspaper advertisements; seeking assistance of friends or relatives; looking for land, building, machinery or equipment to establish own enterprise; arranging for financial resources; and applying for permits and licences. Data are provided by age and geographical coverage, which entails a disaggregation by rural and urban area.